//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.v2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * List of Arrests/Limitations.
 * 
 * <p>Java class for ArrestDetailedInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrestDetailedInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RestrictionBasisDoc" type="{urn:cbr-ru:ed:v2.0}RestrictionBasisDocument" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ArrestID" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}Max10TextType" /&gt;
 *       &lt;attribute name="IndeterminateAmountFlag" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}IndicatorType" /&gt;
 *       &lt;attribute name="ArrestAmount" type="{urn:cbr-ru:ed:leaftypes:v2.0}NotNegativeKopeckAmountType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrestDetailedInfo", propOrder = {
    "restrictionBasisDoc"
})
public class ArrestDetailedInfo {

    @XmlElement(name = "RestrictionBasisDoc")
    protected RestrictionBasisDocument restrictionBasisDoc;
    @XmlAttribute(name = "ArrestID", required = true)
    protected String arrestID;
    @XmlAttribute(name = "IndeterminateAmountFlag", required = true)
    protected boolean indeterminateAmountFlag;
    @XmlAttribute(name = "ArrestAmount")
    protected BigInteger arrestAmount;

    /**
     * Gets the value of the restrictionBasisDoc property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictionBasisDocument }
     *     
     */
    public RestrictionBasisDocument getRestrictionBasisDoc() {
        return restrictionBasisDoc;
    }

    /**
     * Sets the value of the restrictionBasisDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictionBasisDocument }
     *     
     */
    public void setRestrictionBasisDoc(RestrictionBasisDocument value) {
        this.restrictionBasisDoc = value;
    }

    /**
     * Gets the value of the arrestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrestID() {
        return arrestID;
    }

    /**
     * Sets the value of the arrestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrestID(String value) {
        this.arrestID = value;
    }

    /**
     * Gets the value of the indeterminateAmountFlag property.
     * 
     */
    public boolean isIndeterminateAmountFlag() {
        return indeterminateAmountFlag;
    }

    /**
     * Sets the value of the indeterminateAmountFlag property.
     * 
     */
    public void setIndeterminateAmountFlag(boolean value) {
        this.indeterminateAmountFlag = value;
    }

    /**
     * Gets the value of the arrestAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getArrestAmount() {
        return arrestAmount;
    }

    /**
     * Sets the value of the arrestAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setArrestAmount(BigInteger value) {
        this.arrestAmount = value;
    }

}
