//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Корреспондент.
 * 
 * <p>Java class for CashCorrespondentInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CashCorrespondentInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="BICCorr" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}BICRUIDType" /&gt;
 *       &lt;attribute name="CorrAcc" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}AccountNumberRUIDType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CashCorrespondentInfo")
public class CashCorrespondentInfo {

    @XmlAttribute(name = "BICCorr", required = true)
    protected String bicCorr;
    @XmlAttribute(name = "CorrAcc", required = true)
    protected String corrAcc;

    /**
     * Gets the value of the bicCorr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBICCorr() {
        return bicCorr;
    }

    /**
     * Sets the value of the bicCorr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBICCorr(String value) {
        this.bicCorr = value;
    }

    /**
     * Gets the value of the corrAcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrAcc() {
        return corrAcc;
    }

    /**
     * Sets the value of the corrAcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrAcc(String value) {
        this.corrAcc = value;
    }

}
