//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.v2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import open.code.leaftypes.v2.ReasonCodeType;
import open.code.leaftypes.v2.RequestCodeType;


/**
 * Full National BIC Directory/ National BIC Directory Changes
 * 
 * <p>Java class for ED807 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ED807"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:cbr-ru:ed:v2.0}ESIDWithPartInfo"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BICDirectoryEntry" type="{urn:cbr-ru:ed:v2.0}BICDirectoryEntryType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="CreationReason" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}ReasonCodeType" /&gt;
 *       &lt;attribute name="CreationDateTime" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}DateTimeType" /&gt;
 *       &lt;attribute name="InfoTypeCode" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}RequestCodeType" /&gt;
 *       &lt;attribute name="BusinessDay" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}DateType" /&gt;
 *       &lt;attribute name="DirectoryVersion" type="{urn:cbr-ru:ed:leaftypes:v2.0}Max2NumberType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ED807", propOrder = {
    "bicDirectoryEntry"
})
public class ED807
    extends ESIDWithPartInfo
{

    @XmlElement(name = "BICDirectoryEntry")
    protected List<BICDirectoryEntryType> bicDirectoryEntry;
    @XmlAttribute(name = "CreationReason", required = true)
    protected ReasonCodeType creationReason;
    @XmlAttribute(name = "CreationDateTime", required = true)
    protected XMLGregorianCalendar creationDateTime;
    @XmlAttribute(name = "InfoTypeCode", required = true)
    protected RequestCodeType infoTypeCode;
    @XmlAttribute(name = "BusinessDay", required = true)
    protected XMLGregorianCalendar businessDay;
    @XmlAttribute(name = "DirectoryVersion")
    protected BigInteger directoryVersion;

    /**
     * Gets the value of the bicDirectoryEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bicDirectoryEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBICDirectoryEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BICDirectoryEntryType }
     * 
     * 
     */
    public List<BICDirectoryEntryType> getBICDirectoryEntry() {
        if (bicDirectoryEntry == null) {
            bicDirectoryEntry = new ArrayList<BICDirectoryEntryType>();
        }
        return this.bicDirectoryEntry;
    }

    /**
     * Gets the value of the creationReason property.
     * 
     * @return
     *     possible object is
     *     {@link ReasonCodeType }
     *     
     */
    public ReasonCodeType getCreationReason() {
        return creationReason;
    }

    /**
     * Sets the value of the creationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReasonCodeType }
     *     
     */
    public void setCreationReason(ReasonCodeType value) {
        this.creationReason = value;
    }

    /**
     * Gets the value of the creationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDateTime() {
        return creationDateTime;
    }

    /**
     * Sets the value of the creationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDateTime(XMLGregorianCalendar value) {
        this.creationDateTime = value;
    }

    /**
     * Gets the value of the infoTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link RequestCodeType }
     *     
     */
    public RequestCodeType getInfoTypeCode() {
        return infoTypeCode;
    }

    /**
     * Sets the value of the infoTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestCodeType }
     *     
     */
    public void setInfoTypeCode(RequestCodeType value) {
        this.infoTypeCode = value;
    }

    /**
     * Gets the value of the businessDay property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBusinessDay() {
        return businessDay;
    }

    /**
     * Sets the value of the businessDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBusinessDay(XMLGregorianCalendar value) {
        this.businessDay = value;
    }

    /**
     * Gets the value of the directoryVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDirectoryVersion() {
        return directoryVersion;
    }

    /**
     * Sets the value of the directoryVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDirectoryVersion(BigInteger value) {
        this.directoryVersion = value;
    }

}
