//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.v2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * EM referenced group attributes.
 * 
 * <p>Java class for EDRefID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EDRefID"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="EDNo" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}EDNumberType" /&gt;
 *       &lt;attribute name="EDDate" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}DateType" /&gt;
 *       &lt;attribute name="EDAuthor" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}EDDrawerIDType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EDRefID")
@XmlSeeAlso({
    ED.class
})
public class EDRefID {

    @XmlAttribute(name = "EDNo", required = true)
    protected BigInteger edNo;
    @XmlAttribute(name = "EDDate", required = true)
    protected XMLGregorianCalendar edDate;
    @XmlAttribute(name = "EDAuthor", required = true)
    protected String edAuthor;

    /**
     * Gets the value of the edNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEDNo() {
        return edNo;
    }

    /**
     * Sets the value of the edNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEDNo(BigInteger value) {
        this.edNo = value;
    }

    /**
     * Gets the value of the edDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEDDate() {
        return edDate;
    }

    /**
     * Sets the value of the edDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEDDate(XMLGregorianCalendar value) {
        this.edDate = value;
    }

    /**
     * Gets the value of the edAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEDAuthor() {
        return edAuthor;
    }

    /**
     * Sets the value of the edAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEDAuthor(String value) {
        this.edAuthor = value;
    }

}
