//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Информация о транзакционном пакете ЭС
 * 
 * <p>Java class for InitialEDInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InitialEDInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EDRefID" type="{urn:cbr-ru:ed:v2.0}EDRefID"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="PacketStatus" type="{urn:cbr-ru:ed:leaftypes:v2.0}OneDigitCodeType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InitialEDInfo", propOrder = {
    "edRefID"
})
public class InitialEDInfo {

    @XmlElement(name = "EDRefID", required = true)
    protected EDRefID edRefID;
    @XmlAttribute(name = "PacketStatus")
    protected String packetStatus;

    /**
     * Gets the value of the edRefID property.
     * 
     * @return
     *     possible object is
     *     {@link EDRefID }
     *     
     */
    public EDRefID getEDRefID() {
        return edRefID;
    }

    /**
     * Sets the value of the edRefID property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDRefID }
     *     
     */
    public void setEDRefID(EDRefID value) {
        this.edRefID = value;
    }

    /**
     * Gets the value of the packetStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPacketStatus() {
        return packetStatus;
    }

    /**
     * Sets the value of the packetStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPacketStatus(String value) {
        this.packetStatus = value;
    }

}
