//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Condition Parameters.
 * 
 * <p>Java class for LiquidityReservationSchemeParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LiquidityReservationSchemeParameters"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="ConfirmationMessageAuthor" type="{urn:cbr-ru:ed:leaftypes:v2.0}EDDrawerIDType" /&gt;
 *       &lt;attribute name="CancelIfNotReserved" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}IndicatorType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LiquidityReservationSchemeParameters")
public class LiquidityReservationSchemeParameters {

    @XmlAttribute(name = "ConfirmationMessageAuthor")
    protected String confirmationMessageAuthor;
    @XmlAttribute(name = "CancelIfNotReserved", required = true)
    protected boolean cancelIfNotReserved;

    /**
     * Gets the value of the confirmationMessageAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfirmationMessageAuthor() {
        return confirmationMessageAuthor;
    }

    /**
     * Sets the value of the confirmationMessageAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfirmationMessageAuthor(String value) {
        this.confirmationMessageAuthor = value;
    }

    /**
     * Gets the value of the cancelIfNotReserved property.
     * 
     */
    public boolean isCancelIfNotReserved() {
        return cancelIfNotReserved;
    }

    /**
     * Sets the value of the cancelIfNotReserved property.
     * 
     */
    public void setCancelIfNotReserved(boolean value) {
        this.cancelIfNotReserved = value;
    }

}
