//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Информация о лице.
 * 
 * <p>Java class for OfficialPersonInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OfficialPersonInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="HoldPosition" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}Max150TextType" /&gt;
 *       &lt;attribute name="Name" use="required" type="{urn:cbr-ru:ed:leaftypes:v2.0}Max60TextType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OfficialPersonInfo")
public class OfficialPersonInfo {

    @XmlAttribute(name = "HoldPosition", required = true)
    protected String holdPosition;
    @XmlAttribute(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the holdPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoldPosition() {
        return holdPosition;
    }

    /**
     * Sets the value of the holdPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoldPosition(String value) {
        this.holdPosition = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
