//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Дополнительная информация по операции.
 * 
 * <p>Java class for OpRevaluationInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpRevaluationInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OpPreciousMetal" type="{urn:cbr-ru:ed:v2.0}OpPreciousMetal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpRevaluationInfo", propOrder = {
    "opPreciousMetal"
})
public class OpRevaluationInfo {

    @XmlElement(name = "OpPreciousMetal", required = true)
    protected OpPreciousMetal opPreciousMetal;

    /**
     * Gets the value of the opPreciousMetal property.
     * 
     * @return
     *     possible object is
     *     {@link OpPreciousMetal }
     *     
     */
    public OpPreciousMetal getOpPreciousMetal() {
        return opPreciousMetal;
    }

    /**
     * Sets the value of the opPreciousMetal property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpPreciousMetal }
     *     
     */
    public void setOpPreciousMetal(OpPreciousMetal value) {
        this.opPreciousMetal = value;
    }

}
