//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:cbr-ru:ed:v2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package open.code.v2;
