//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Запись Справочника УФ-ЦФ.
 * 
 * <p>Java class for UFCFRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UFCFRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UFBIC" type="{urn:cbr-ru:ed:leaftypes:v2.0}BICRUIDType"/&gt;
 *         &lt;element name="CFBICList" type="{urn:cbr-ru:ed:v2.0}CFBICList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UFCFRecord", propOrder = {
    "ufbic",
    "cfbicList"
})
public class UFCFRecord {

    @XmlElement(name = "UFBIC", required = true)
    protected String ufbic;
    @XmlElement(name = "CFBICList", required = true)
    protected CFBICList cfbicList;

    /**
     * Gets the value of the ufbic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUFBIC() {
        return ufbic;
    }

    /**
     * Sets the value of the ufbic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUFBIC(String value) {
        this.ufbic = value;
    }

    /**
     * Gets the value of the cfbicList property.
     * 
     * @return
     *     possible object is
     *     {@link CFBICList }
     *     
     */
    public CFBICList getCFBICList() {
        return cfbicList;
    }

    /**
     * Sets the value of the cfbicList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFBICList }
     *     
     */
    public void setCFBICList(CFBICList value) {
        this.cfbicList = value;
    }

}
