//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.leaftypes.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccountType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AccountType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}IdentifierTextCategory"&gt;
 *     &lt;enumeration value="BANA"/&gt;
 *     &lt;enumeration value="CBRA"/&gt;
 *     &lt;enumeration value="CRSA"/&gt;
 *     &lt;enumeration value="TRSA"/&gt;
 *     &lt;enumeration value="CLRA"/&gt;
 *     &lt;enumeration value="EPGA"/&gt;
 *     &lt;enumeration value="EPSA"/&gt;
 *     &lt;enumeration value="GARA"/&gt;
 *     &lt;enumeration value="TRUA"/&gt;
 *     &lt;enumeration value="UTRA"/&gt;
 *     &lt;enumeration value="CLAC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AccountType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum AccountType {

    BANA,
    CBRA,
    CRSA,
    TRSA,
    CLRA,
    EPGA,
    EPSA,
    GARA,
    TRUA,
    UTRA,
    CLAC;

    public String value() {
        return name();
    }

    public static AccountType fromValue(String v) {
        return valueOf(v);
    }

}
