//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.leaftypes.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccRstrCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AccRstrCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CLRS"/&gt;
 *     &lt;enumeration value="LMRS"/&gt;
 *     &lt;enumeration value="URRS"/&gt;
 *     &lt;enumeration value="PSRS"/&gt;
 *     &lt;enumeration value="ESRS"/&gt;
 *     &lt;enumeration value="SCRS"/&gt;
 *     &lt;enumeration value="MVRS"/&gt;
 *     &lt;enumeration value="RTRS"/&gt;
 *     &lt;enumeration value="FSRS"/&gt;
 *     &lt;enumeration value="LSRS"/&gt;
 *     &lt;enumeration value="QPRS"/&gt;
 *     &lt;enumeration value="SDRS"/&gt;
 *     &lt;enumeration value="SMRS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AccRstrCodeType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum AccRstrCodeType {

    CLRS,
    LMRS,
    URRS,
    PSRS,
    ESRS,
    SCRS,
    MVRS,
    RTRS,
    FSRS,
    LSRS,
    QPRS,
    SDRS,
    SMRS;

    public String value() {
        return name();
    }

    public static AccRstrCodeType fromValue(String v) {
        return valueOf(v);
    }

}
