//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.leaftypes.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClearingCodeListType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ClearingCodeListType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}IdentifierTextCategory"&gt;
 *     &lt;enumeration value="VISA"/&gt;
 *     &lt;enumeration value="MASC"/&gt;
 *     &lt;enumeration value="MIRC"/&gt;
 *     &lt;enumeration value="UPAY"/&gt;
 *     &lt;enumeration value="JCBC"/&gt;
 *     &lt;enumeration value="AMES"/&gt;
 *     &lt;enumeration value="FSSC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ClearingCodeListType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum ClearingCodeListType {

    VISA,
    MASC,
    MIRC,
    UPAY,
    JCBC,
    AMES,
    FSSC;

    public String value() {
        return name();
    }

    public static ClearingCodeListType fromValue(String v) {
        return valueOf(v);
    }

}
