//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.leaftypes.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ED307AccountStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ED307AccountStatusType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}IdentifierTextCategory"&gt;
 *     &lt;enumeration value="ACWA"/&gt;
 *     &lt;enumeration value="ACAC"/&gt;
 *     &lt;enumeration value="ACWD"/&gt;
 *     &lt;enumeration value="ACDL"/&gt;
 *     &lt;enumeration value="ACDE"/&gt;
 *     &lt;enumeration value="ACSE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ED307AccountStatusType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum ED307AccountStatusType {

    ACWA,
    ACAC,
    ACWD,
    ACDL,
    ACDE,
    ACSE;

    public String value() {
        return name();
    }

    public static ED307AccountStatusType fromValue(String v) {
        return valueOf(v);
    }

}
