//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.leaftypes.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FTIGroupCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FTIGroupCodeType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}CodeCategory"&gt;
 *     &lt;enumeration value="CND1"/&gt;
 *     &lt;enumeration value="CND2"/&gt;
 *     &lt;enumeration value="INTR"/&gt;
 *     &lt;enumeration value="QWRH"/&gt;
 *     &lt;enumeration value="QWAP"/&gt;
 *     &lt;enumeration value="QSPC"/&gt;
 *     &lt;enumeration value="QWCH"/&gt;
 *     &lt;enumeration value="QWEC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FTIGroupCodeType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum FTIGroupCodeType {

    @XmlEnumValue("CND1")
    CND_1("CND1"),
    @XmlEnumValue("CND2")
    CND_2("CND2"),
    INTR("INTR"),
    QWRH("QWRH"),
    QWAP("QWAP"),
    QSPC("QSPC"),
    QWCH("QWCH"),
    QWEC("QWEC");
    private final String value;

    FTIGroupCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FTIGroupCodeType fromValue(String v) {
        for (FTIGroupCodeType c: FTIGroupCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
