//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.leaftypes.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LimitType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LimitType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}CodeCategory"&gt;
 *     &lt;enumeration value="FIPL"/&gt;
 *     &lt;enumeration value="FPML"/&gt;
 *     &lt;enumeration value="ICLL"/&gt;
 *     &lt;enumeration value="IOCL"/&gt;
 *     &lt;enumeration value="IPCL"/&gt;
 *     &lt;enumeration value="NURL"/&gt;
 *     &lt;enumeration value="TCLL"/&gt;
 *     &lt;enumeration value="URGL"/&gt;
 *     &lt;enumeration value="VIPL"/&gt;
 *     &lt;enumeration value="VPML"/&gt;
 *     &lt;enumeration value="IPIL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LimitType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum LimitType {

    FIPL,
    FPML,
    ICLL,
    IOCL,
    IPCL,
    NURL,
    TCLL,
    URGL,
    VIPL,
    VPML,
    IPIL;

    public String value() {
        return name();
    }

    public static LimitType fromValue(String v) {
        return valueOf(v);
    }

}
