//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.leaftypes.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationTextType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OperationTextType"&gt;
 *   &lt;restriction base="{urn:cbr-ru:ed:basetypes:v2.0}CodeCategory"&gt;
 *     &lt;enumeration value="AAAC"/&gt;
 *     &lt;enumeration value="APAC"/&gt;
 *     &lt;enumeration value="CHNG"/&gt;
 *     &lt;enumeration value="CWAC"/&gt;
 *     &lt;enumeration value="NSRE"/&gt;
 *     &lt;enumeration value="NSRP"/&gt;
 *     &lt;enumeration value="FORE"/&gt;
 *     &lt;enumeration value="OTAE"/&gt;
 *     &lt;enumeration value="OTAP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OperationTextType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum OperationTextType {

    AAAC,
    APAC,
    CHNG,
    CWAC,
    NSRE,
    NSRP,
    FORE,
    OTAE,
    OTAP;

    public String value() {
        return name();
    }

    public static OperationTextType fromValue(String v) {
        return valueOf(v);
    }

}
