//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.17 at 07:21:09 PM GST 
//


package open.code.leaftypes.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OperationType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CCPH"/&gt;
 *     &lt;enumeration value="CCRC"/&gt;
 *     &lt;enumeration value="CCRB"/&gt;
 *     &lt;enumeration value="CCPL"/&gt;
 *     &lt;enumeration value="CBPH"/&gt;
 *     &lt;enumeration value="CBPP"/&gt;
 *     &lt;enumeration value="CBRC"/&gt;
 *     &lt;enumeration value="CBRB"/&gt;
 *     &lt;enumeration value="CCRD"/&gt;
 *     &lt;enumeration value="CCRT"/&gt;
 *     &lt;enumeration value="CCRN"/&gt;
 *     &lt;enumeration value="CBRD"/&gt;
 *     &lt;enumeration value="CBRT"/&gt;
 *     &lt;enumeration value="CBRN"/&gt;
 *     &lt;enumeration value="BCPH"/&gt;
 *     &lt;enumeration value="BCRC"/&gt;
 *     &lt;enumeration value="BCRB"/&gt;
 *     &lt;enumeration value="BCRD"/&gt;
 *     &lt;enumeration value="BCRT"/&gt;
 *     &lt;enumeration value="BCRN"/&gt;
 *     &lt;enumeration value="BBPH"/&gt;
 *     &lt;enumeration value="BBRT"/&gt;
 *     &lt;enumeration value="BBRN"/&gt;
 *     &lt;enumeration value="BBRB"/&gt;
 *     &lt;enumeration value="BBRD"/&gt;
 *     &lt;enumeration value="BBRC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OperationType", namespace = "urn:cbr-ru:ed:leaftypes:v2.0")
@XmlEnum
public enum OperationType {

    CCPH,
    CCRC,
    CCRB,
    CCPL,
    CBPH,
    CBPP,
    CBRC,
    CBRB,
    CCRD,
    CCRT,
    CCRN,
    CBRD,
    CBRT,
    CBRN,
    BCPH,
    BCRC,
    BCRB,
    BCRD,
    BCRT,
    BCRN,
    BBPH,
    BBRT,
    BBRN,
    BBRB,
    BBRD,
    BBRC;

    public String value() {
        return name();
    }

    public static OperationType fromValue(String v) {
        return valueOf(v);
    }

}
